# fluent-bit 구성 정보 -> 설정 -> 작동
# ---------------------
# 서비스 정의, 전역 설정
# 로그 1개당 전송, 전송과정에 대한 로그는 info 레벨만 확인
# ---------------------
[SERVICE]
    Flush           1
    Log_Level       info
    Parsers_File    /fluent-bit/etc/parsers.conf

# ---------------------
# 입력 (로그 수집) -> 2개 (xx_json.log, xx_text.log)
# tail을 이용하여 마지막에 추가된 로그를 획득, 감시하는 파일(Path)
# DB는 현재 로그파일에서 어디까지 읽었는지 기록(인덱스, 파일포인터 위치)
# 로그 파일로테이션시 5초간 대기, 
# ---------------------
[INPUT]
    Name              tail
    Path              /opt/airflow/sensor_logs/sensor_json.log
    Tag               sensor.json
    Parser            json
    DB                /fluent-bit/state/sensor-json.db
    DB.Sync           Normal
    Refresh_Interval  1
    Rotate_Wait       5
    Skip_Long_Lines   On

    # macOS Docker bind mount에서는 inotify 대신 stat polling 사용
    Inotify_Watcher   false

# 비정형 데이터 (text) 읽기
[INPUT]
    Name              tail
    Path              /opt/airflow/sensor_logs/sensor_text.log
    Tag               sensor.text    
    DB                /fluent-bit/state/sensor-text.db
    DB.Sync           Normal
    Refresh_Interval  1
    Rotate_Wait       5
    Skip_Long_Lines   On

    # macOS Docker bind mount에서는 inotify 대신 stat polling 사용
    Inotify_Watcher   false

# ---------------------
# 출력 (로그 전송) -> 2개(실제 전달, kafka(json), logstash(text)) + 2개(모니터링용, 임시 편성)
# ---------------------
# 임시 편성, 데이터를 잘 읽고 있는지 확인하는 용도, 나중에 제거
# 데이터에 태깅된 정보를 기반으로 필터링 하여 출력
[OUTPUT]
    Name        stdout
    Match       sensor.json

[OUTPUT]
    Name        stdout
    Match       sensor.text