input {
    # http 5044번 입력
    http {
        port => 5044
    }
}
filter {
    # Grok이라는 도구를 이용하여 비정형 데이터 => 반정형 데이터 변환 처리
    # message => 원본 테스트 데이터
    # 조건 : 텍스트 데이터에 "ID=" 표현이 포함되는 경우만 처리함 => 임시 구성
    if [message] =~ "ID=" {
        # 변환 처리 => { 키:값, .....}
        # %{패턴명:필드명:데이터타입} or %{패턴명:필드명}
        grok {
            match => { "message" => "\[%{TIMESTAMP_ISO8601:log_time}\] ID=%{DATA:device_id} \|   TEMP:%{NUMBER:temp:float} \|   HUMI:%{NUMBER:humi:float} \|   STAT:%{WORD:status}" }
        }
    }
}
output {
    # Kafka 브로커 전달 (9092)
    kafka {
        bootstrap_servers => "kafka:9092"
        topic_id => "factory-text-topic"
        codec => json
    }
    # 디버깅용 콘솔출력
    stdout {
        codec => rubydebug
    }
}